Fix/instructions
EEBOS/frontend-assessment-course-list pull request #6
Opened 2022-02-18 15:21 UTC by aubeOSG

- Removed some of the requirements of the controls tasks to reducing the time need to complete the assessment.
- Changed some language and fixed some grammar and spelling mistakes

2022-02-18 21:32 UTC, CiceroFonsecaOSG requested changes
Small feedback @aubeOSG, other than that, I think this is in pretty good shape 👌

2022-02-18 21:32 UTC, CiceroFonsecaOSG commented on README.md
> +> One the dependencies is [parcelJS](https://parceljs.org/) (you don't need an understanding of parcel for this assessment) you may need to install this package globally. `npm install parcel -D -g`
Can we move it up above the `npm install`? 

This way the candidate can install parcelJS before trying to run `npm install` and get an error, for sure there will be someone who will copy/paste/run and then read the parcelJS instruction 😅

2022-02-18 21:32 UTC, CiceroFonsecaOSG commented on README.md
> +A dropdown menu containing the options below which are fields that can be sorted on and radio button group indicating sort order.
I'm kind of confused here. 

This should be a dropdown with two groups, the first group is the sort option (title, created) and the second one the sort order (asc, desc), right? The `low to high` and `high to low` will not be used once we got rid of the number sort options, is this correct?

2022-02-24 13:18 UTC, SezarGantousOSG approved these changes
Other than what @CiceroFonsecaOSG is suggesting I think you did make it better and easier to ready through. I think the tables you added helps quite a bit.

2022-02-25 20:54 UTC, merged